### ISSUE TITLE
Pod runs in crashloop

### ISSUE THREAD

**Issue by hikhvar** [stackabletech/zookeeper-operator#357]
My Zookeeper Pod does not start, since the init container crashes:
```
kubectl get pod/stackable-zookeeper-server-default-0                                                                                         
NAME                                   READY   STATUS                  RESTARTS   AGE
stackable-zookeeper-server-default-0   0/1     Init:CrashLoopBackOff   17         67m
```
It seems that there is a permission error in the image:
```
kubectl logs -f pod/stackable-zookeeper-server-default-0 -c decide-myid                                                                 
sh: /stackable/data/myid: Permission denied
```

Image of Zookeeper Pod: `docker.stackable.tech/stackable/zookeeper:3.5.8-stackable0`
Version of Zookeeper Operator: `docker.stackable.tech/stackable/zookeeper-operator:0.8.0`

Zookeeper Cluster CRD to reproduce:
```
kubectl get zookeeperclusters stackable-zookeeper -o yaml                                                                                 

apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  annotations:
  name: stackable-zookeeper
  namespace: default
spec:
  servers:
    roleGroups:
      default:
        config:
          adminPort: 12000
          clientPort: 2181
          dataDir: /var/lib/zookeeper
          initLimit: 5
          metricsPort: 9505
          syncLimit: 2
        replicas: 3
        selector:
          matchLabels:
            kubernetes.io/os: linux
  version: 3.5.8
```
