### ISSUE TITLE
TLS authentication & encryption

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/zookeeper-operator#466]

**Comment by soenkeliebau** [comment]
I have just discussed this with Malte a bit and done a mini-refinement as well as some designing which I'd like to leave here for others to comment on (most notably @teozkr and @sbernauer as this builds on / changes code by them).

ZooKeeper allows configuration of [inter-quorum communication](https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#Quorum+TLS) as well as communication with clients separately, so we probably need to support this is separate settings as well.

Generic tls settings are documented (badly) here: https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_authOptions

Since this ticket mentions both encryption and authentication we assumed that both should be implemented as part of this issue, which would leave us with the following items:

- [ ] Make encryption on quorum ports configurable
- [ ] Make encryption on client ports configurable
- [ ] Make authentication on quorum ports configurable
- [ ] Make authentication on client ports configurable

Debatable:
- [ ] Extend znode (or rather the ConfigMap generated in response to the znode) to contain information on which SecretClass/AuthenticationClass should be used to authenticate against this service instance

**Implementation suggestion:**

We discussed how this could look in the CRD a bit and came up with the following, which would configure ZooKeeper to require client certs for internal comms (i.e. other ZooKeeper nodes) and allow clients to simply connect unauthenticated but encrypted.


```yaml
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: ssl-zk
spec:
  config:
    tlsAuthenticationConfig:
      quorum:
        authenticationClass: zookeeper-tls-mutual
      clients:
        authenticationClass: zookeeper-tls
  servers:
    roleGroups:
      primary:
        replicas: 2
        config:
          myidOffset: 10
      secondary:
        replicas: 1
        config:
          myidOffset: 20
  version: 3.8.0
  stopped: false
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: zookeeper-tls
spec:
  provider:
    tls:
      verification:
        server:
          caCert:
            secretClass: tls
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: zookeeper-tls-mutual
spec:
  provider:
    tls:
      verification:
        mutual:
          caCert:
            secretClass: tls
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: default
        autoGenerate: true
```


Some changes to the framework would be needed for this, most notably adding a new Variant to the [AuthenticationClass](https://github.com/stackabletech/operator-rs/blob/main/src/commons/authentication.rs#L27) enum to represent TLS authentication. But we feel that this is in line with the intention for this enum anyway.
