### ISSUE TITLE
Client TLS cannot be disabled

### ISSUE THREAD

**Issue by maltesander** [stackabletech/zookeeper-operator#528]
Came up when implementing TLS for Trino. Currently when setting `tls.secretClass: null`
```
spec:
  version: 3.8.0-stackable0.7.1
  config:
    tls: null
    clientAuthentication:
      authenticationClass: zk-client-tls
    quorumTlsSecretClass: tls
```
to disable client TLS, it defaults to the "tls" SecretClass. This is due to wrong defaults in the code.
