### ISSUE TITLE
Zookeeper primary pod won't start

### ISSUE THREAD

**Issue by snocke** [stackabletech/zookeeper-operator#546]
### Affected version

3.8.0

### Current and expected behavior

I wanted to set up a zookeeper cluster with primary and secondary setup. Just like the [integration test](https://github.com/stackabletech/zookeeper-operator/blob/main/tests/templates/kuttl/smoke/00-install-zookeeper.yaml.j2)

However, just the primary-0 won't start. Please see the log and setup below

### Additional context

<img width="2323" alt="grafik" src="https://user-images.githubusercontent.com/9850483/187512379-2767f219-fc25-4565-ada5-eb98a480c932.png">

<img width="2401" alt="grafik" src="https://user-images.githubusercontent.com/9850483/187512698-b1c293a8-3254-4682-a93e-05471dd15e2f.png">

### Environment

Mac M1
MacOs Montery 12.5
docker image explicitly build for ARM machines 
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.0

[zookeeper.log.txt](https://github.com/stackabletech/zookeeper-operator/files/9455559/zookeeper.log.txt)
[zookeeper.yaml.txt](https://github.com/stackabletech/zookeeper-operator/files/9455560/zookeeper.yaml.txt)

### Would you like to work on fixing this bug?

maybe

**Comment by teozkr** [comment]
Looks like ZooKeeper node ID confusion.

If you use multiple rolegroups then you need to configure `myidOffset` per rolegroup so that the sequences of `myidOffset .. myidOffset + replicas` don't overlap.

For example, you could change your `ZookeeperCluster` to:

```yaml
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  config:
    quorumTlsSecretClass: tls
  servers:
    roleGroups:
      primary:
        replicas: 2
      secondary:
        replicas: 1
        config:
          myidOffset: 10
  version: 3.8.0-stackable0.99.0
  stopped: false
```
