### ISSUE TITLE
`bash: /stackable/data/myid: Permission denied`

### ISSUE THREAD

**Issue by Nicklason** [stackabletech/zookeeper-operator#727]
### Affected version

23.7.0

### Current and expected behavior

Steps to reproduce:

1. Start minikube `minikube start`
2. Install operators (hdfs-operator, zookeeper-operator, commons-operator, secret-operator)
3. Cordon node `kubectl cordon minikube`
4. Add a worker node `minikube node add`
5. Apply ZooKeeperCluster resource (see below)
6. Pod status `Init:CrashLoopBackOff`

I apply a basic ZookeeperCluster resource. It creates one pod but the init container crashes and the pod is stuck in `Init:CrashLoopBackOff`.

### Possible solution

If the zookeeper pod runs on the "minikube" node (the controlplane node) then it works, but if it runs on a worker node then it does not work.

This issue may be related to #357.

### Additional context

ZooKeeper cluster:
```yaml
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
    stackableVersion: 23.7.0
  servers:
    roleGroups:
      default:
        replicas: 1
```

Error:
```bash
kubectl logs pods/simple-zk-server-default-0 prepare -f
copying /stackable/config to /stackable/rwconfig
bash: /stackable/data/myid: Permission denied
```

### Environment

minikube cluster using docker driver with one control plane node and one worker node.

Kubernetes v1.27.4
minikube: v1.31.2
zookeeper-operator: v23.7.0

### Would you like to work on fixing this bug?

None
